import { Injectable } from '@angular/core';
import { AngularFirestore, AngularFirestoreCollection} from '@angular/fire/compat/firestore/';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { Tienda } from '../interface/tiendas.interface';

@Injectable({
  providedIn: 'root'
})
export class TiendasService {

  private itemsCollection: AngularFirestoreCollection<any>
  // public tiendas: Tienda[]= [];
  // public usuario: any = {}
  public tiendas: Tienda[] = [
    {
      "SAP": "T173",
      "ACTIVO": 21090018,
      "TIENDA": "Cac Plaza Patio Pachuca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ SANDOVAL JUAN RAMON",
      "STATUS": "",
      "IDPDV": 21090018
    },
    {
      "SAP": "T277",
      "ACTIVO": 99090060,
      "TIENDA": "Cac Tecamac",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ SANDOVAL JUAN RAMON",
      "STATUS": "",
      "IDPDV": 99090060
    },
    {
      "SAP": "T548",
      "ACTIVO": 99090127,
      "TIENDA": "Mini Cac Explanada Pachuca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ SANDOVAL JUAN RAMON",
      "STATUS": "",
      "IDPDV": 99090127
    },
    {
      "SAP": "T456",
      "ACTIVO": 99090093,
      "TIENDA": "Mini Cac Galerias Pachuca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ SANDOVAL JUAN RAMON",
      "STATUS": "",
      "IDPDV": 99090093
    },
    {
      "SAP": "T276",
      "ACTIVO": 99090057,
      "TIENDA": "Mini Cac Pachuca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ SANDOVAL JUAN RAMON",
      "STATUS": "",
      "IDPDV": 99090057
    },
    {
      "SAP": "T195",
      "ACTIVO": 21090034,
      "TIENDA": "Mini Cac Patio Tulancingo",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ SANDOVAL JUAN RAMON",
      "STATUS": "",
      "IDPDV": 21090034
    },
    {
      "SAP": "T440",
      "ACTIVO": 99090086,
      "TIENDA": "Mini Cac Town Center Zumpango",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ SANDOVAL JUAN RAMON",
      "STATUS": "",
      "IDPDV": 99090086
    },
    {
      "SAP": "T163",
      "ACTIVO": 38090004,
      "TIENDA": "Cac Coacalco",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 38090004
    },
    {
      "SAP": "T389",
      "ACTIVO": 99090064,
      "TIENDA": "Cac Patio Ecatepec",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 99090064
    },
    {
      "SAP": "T405",
      "ACTIVO": 99090070,
      "TIENDA": "Mini Cac Plaza Ca�ada Huehuetoca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 99090070
    },
    {
      "SAP": "T438",
      "ACTIVO": 99090084,
      "TIENDA": "Mini Cac Plaza Coacalco",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 99090084
    },
    {
      "SAP": "T224",
      "ACTIVO": 99090004,
      "TIENDA": "Smart Store Las Americas",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 99090004
    },
    {
      "SAP": "T289",
      "ACTIVO": 99090050,
      "TIENDA": "Smart Store Plaza Cosmopol",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 99090050
    },
    {
      "SAP": "T525",
      "ACTIVO": 99090113,
      "TIENDA": "Cac Arkana Norte Cuautitlan Izcalli",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 99090113
    },
    {
      "SAP": "T176",
      "ACTIVO": 38090003,
      "TIENDA": "Cac San Marcos Cuautitlan",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 38090003
    },
    {
      "SAP": "T192",
      "ACTIVO": 21090029,
      "TIENDA": "Mini Cac Luna Park",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 21090029
    },
    {
      "SAP": "T597",
      "ACTIVO": 99090141,
      "TIENDA": "Movistar Centro San Miguel Cuautitlan",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ PENSAMIENTO TANIA IVETTE",
      "STATUS": "",
      "IDPDV": 99090141
    },
    {
      "SAP": "T170",
      "ACTIVO": 99090027,
      "TIENDA": "Cac Metepec Edo Mex",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 99090027
    },
    {
      "SAP": "T445",
      "ACTIVO": 99090085,
      "TIENDA": "Cac Miguel Hidalgo Toluca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 99090085
    },
    {
      "SAP": "T395",
      "ACTIVO": 99090066,
      "TIENDA": "Cac Plaza Mia Zinacantepec",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 99090066
    },
    {
      "SAP": "T191",
      "ACTIVO": 21090047,
      "TIENDA": "Mini Cac Lerma",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 21090047
    },
    {
      "SAP": "T193",
      "ACTIVO": 21090033,
      "TIENDA": "Mini Cac Mariano Matamoros",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 21090033
    },
    {
      "SAP": "T376",
      "ACTIVO": 99090063,
      "TIENDA": "Mini Cac Paseo El Sol Toluca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 99090063
    },
    {
      "SAP": "T198",
      "ACTIVO": 21090038,
      "TIENDA": "Mini Cac Plaza Estrella Atlacomulco",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 21090038
    },
    {
      "SAP": "T471",
      "ACTIVO": 99090100,
      "TIENDA": "Mini Cac Sendero Toluca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 99090100
    },
    {
      "SAP": "T598",
      "ACTIVO": 99090142,
      "TIENDA": "Movistar Patio Toluca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 99090142
    },
    {
      "SAP": "T599",
      "ACTIVO": 99090143,
      "TIENDA": "Movistar Plaza Town Square Metepec",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RODRIGUEZ GAYTAN FERNANDO",
      "STATUS": "",
      "IDPDV": 99090143
    },
    {
      "SAP": "T164",
      "ACTIVO": 99090030,
      "TIENDA": "Cac Costera Acapulco",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 99090030
    },
    {
      "SAP": "T165",
      "ACTIVO": 21090026,
      "TIENDA": "Cac Cuernavaca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 21090026
    },
    {
      "SAP": "T412",
      "ACTIVO": 99090072,
      "TIENDA": "Cac Domingo Diez Cuernavaca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 99090072
    },
    {
      "SAP": "T451",
      "ACTIVO": 99090090,
      "TIENDA": "Cac Forum Cuernavaca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 99090090
    },
    {
      "SAP": "T399",
      "ACTIVO": 99090068,
      "TIENDA": "Cac Walmart Jiutepec",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 99090068
    },
    {
      "SAP": "T274",
      "ACTIVO": 99090058,
      "TIENDA": "Mini Cac Cuautla",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 99090058
    },
    {
      "SAP": "T184",
      "ACTIVO": 21090028,
      "TIENDA": "Mini Cac Gran Plaza Acapulco",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 21090028
    },
    {
      "SAP": "T185",
      "ACTIVO": 21090039,
      "TIENDA": "Mini Cac Plaza Atrios",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 21090039
    },
    {
      "SAP": "T469",
      "ACTIVO": 99090099,
      "TIENDA": "Mini Cac Plaza Averanda Cuernavaca",
      "REGION": "",
      "TERRITORIO": "Centro Foraneo",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ESPINOZA MENDOZA MIGUEL ANGEL NICOLAS",
      "STATUS": "",
      "IDPDV": 99090099
    },
    {
      "SAP": "T160",
      "ACTIVO": 99090028,
      "TIENDA": "Cac Buenavista",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090028
    },
    {
      "SAP": "T362",
      "ACTIVO": 99090062,
      "TIENDA": "Cac La Cuspide",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090062
    },
    {
      "SAP": "T177",
      "ACTIVO": 38090002,
      "TIENDA": "Cac Satelite Edo Mex",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 38090002
    },
    {
      "SAP": "T430",
      "ACTIVO": 99090077,
      "TIENDA": "Mini Cac Galerias Atizapan",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090077
    },
    {
      "SAP": "T194",
      "ACTIVO": 21090040,
      "TIENDA": "Mini Cac Nicolas Romero",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 21090040
    },
    {
      "SAP": "T590",
      "ACTIVO": 99090137,
      "TIENDA": "Movistar Mundo E",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090137
    },
    {
      "SAP": "T606",
      "ACTIVO": 99090146,
      "TIENDA": "Movistar Plaza Crystal Atizapan",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090146
    },
    {
      "SAP": "T605",
      "ACTIVO": 99090145,
      "TIENDA": "Movistar Plaza Millenium Tlalnepantla",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090145
    },
    {
      "SAP": "T612",
      "ACTIVO": 99090151,
      "TIENDA": "Movistar Plaza Satelite Ii",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090151
    },
    {
      "SAP": "T584",
      "ACTIVO": 99090135,
      "TIENDA": "Movistar Plaza Sentura Tlalnepantla",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090135
    },
    {
      "SAP": "T292",
      "ACTIVO": 99090056,
      "TIENDA": "Smart Store Plaza Satelite",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090056
    },
    {
      "SAP": "T459",
      "ACTIVO": 99090094,
      "TIENDA": "Cac Chimalhuacan Neza",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 99090094
    },
    {
      "SAP": "T516",
      "ACTIVO": 99090112,
      "TIENDA": "Cac Las Antenas Iztapalapa",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 99090112
    },
    {
      "SAP": "T400",
      "ACTIVO": 99090069,
      "TIENDA": "Cac Plaza Centro Chalco",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 99090069
    },
    {
      "SAP": "T178",
      "ACTIVO": 99090029,
      "TIENDA": "Cac Texcoco",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 99090029
    },
    {
      "SAP": "T187",
      "ACTIVO": 21090030,
      "TIENDA": "Mini Cac Plaza Zentralia",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 21090030
    },
    {
      "SAP": "T188",
      "ACTIVO": 21090044,
      "TIENDA": "Mini Cac Portal Churubusco",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 21090044
    },
    {
      "SAP": "T512",
      "ACTIVO": 99090105,
      "TIENDA": "Mini Cac Portal Lomas Estrella",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090105
    },
    {
      "SAP": "T587",
      "ACTIVO": 99090136,
      "TIENDA": "Movistar Patio Valle De Chalco",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 99090136
    },
    {
      "SAP": "T596",
      "ACTIVO": 99090140,
      "TIENDA": "Movistar Plaza Centro Tepozan",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 99090140
    },
    {
      "SAP": "T619",
      "ACTIVO": 99090177,
      "TIENDA": "Movistar Puerta Aragon",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 99090177
    },
    {
      "SAP": "T604",
      "ACTIVO": 99090144,
      "TIENDA": "Movistar Uami Iztapalapa",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 99090144
    },
    {
      "SAP": "T158",
      "ACTIVO": 21090021,
      "TIENDA": "Cac Aeropuerto",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 21090021
    },
    {
      "SAP": "T162",
      "ACTIVO": 21090020,
      "TIENDA": "Cac Centro Historico",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 21090020
    },
    {
      "SAP": "T171",
      "ACTIVO": 99090024,
      "TIENDA": "Cac Plaza Aragon Edo Mex",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 99090024
    },
    {
      "SAP": "T431",
      "ACTIVO": 99090078,
      "TIENDA": "Isla Reforma 222",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 99090078
    },
    {
      "SAP": "T484",
      "ACTIVO": 99090102,
      "TIENDA": "Mini Cac Plaza Tlatelolco Cdmx",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 99090102
    },
    {
      "SAP": "T421",
      "ACTIVO": 99090073,
      "TIENDA": "Mini Cac Portal Centro",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 99090073
    },
    {
      "SAP": "T591",
      "ACTIVO": 99090138,
      "TIENDA": "Movistar Multiplaza Aragon",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 99090138
    },
    {
      "SAP": "T623",
      "ACTIVO": 99090182,
      "TIENDA": "Movistar Parque Delta",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090182
    },
    {
      "SAP": "T220",
      "ACTIVO": 99090003,
      "TIENDA": "Smart Store Galeria De Las Estrellas",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 99090003
    },
    {
      "SAP": "T231",
      "ACTIVO": 99090005,
      "TIENDA": "Smart Store Republica De Uruguay",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 99090005
    },
    {
      "SAP": "T172",
      "ACTIVO": 99090026,
      "TIENDA": "Cac Plaza Lindavista",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MIRANDA VELAZQUEZ CLAUDIA",
      "STATUS": "",
      "IDPDV": 99090026
    },
    {
      "SAP": "T175",
      "ACTIVO": 21090014,
      "TIENDA": "Cac Rosario",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MIRANDA VELAZQUEZ CLAUDIA",
      "STATUS": "",
      "IDPDV": 21090014
    },
    {
      "SAP": "T179",
      "ACTIVO": 99090025,
      "TIENDA": "Cac Tezontle",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MIRANDA VELAZQUEZ CLAUDIA",
      "STATUS": "",
      "IDPDV": 99090025
    },
    {
      "SAP": "T532",
      "ACTIVO": 99090115,
      "TIENDA": "Cac Tlalnepantla Centro",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MIRANDA VELAZQUEZ CLAUDIA",
      "STATUS": "",
      "IDPDV": 99090115
    },
    {
      "SAP": "T433",
      "ACTIVO": 99090080,
      "TIENDA": "Isla Parque Tezontle",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MIRANDA VELAZQUEZ CLAUDIA",
      "STATUS": "",
      "IDPDV": 99090080
    },
    {
      "SAP": "T501",
      "ACTIVO": 99090103,
      "TIENDA": "Mini Cac Encuentro Fortuna",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99090103
    },
    {
      "SAP": "T536",
      "ACTIVO": 99090117,
      "TIENDA": "Mini Cac Las Tiendas De San Esteban Naucalpan",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090117
    },
    {
      "SAP": "T410",
      "ACTIVO": 99090071,
      "TIENDA": "Mini Cac Parque Via Vallejo",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MIRANDA VELAZQUEZ CLAUDIA",
      "STATUS": "",
      "IDPDV": 99090071
    },
    {
      "SAP": "T422",
      "ACTIVO": 99090074,
      "TIENDA": "Mini Cac Pasaje Ferreria Azcapotzalco",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090074
    },
    {
      "SAP": "T443",
      "ACTIVO": 99090088,
      "TIENDA": "Mini Cac Plaza Tepeyac Cdmx",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MIRANDA VELAZQUEZ CLAUDIA",
      "STATUS": "",
      "IDPDV": 99090088
    },
    {
      "SAP": "T622",
      "ACTIVO": 99090181,
      "TIENDA": "Movistar Parque Lindavista",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MIRANDA VELAZQUEZ CLAUDIA",
      "STATUS": "",
      "IDPDV": 99090181
    },
    {
      "SAP": "T621",
      "ACTIVO": 99090180,
      "TIENDA": "Movistar Parque Toreo",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090180
    },
    {
      "SAP": "T608",
      "ACTIVO": 99090148,
      "TIENDA": "Movistar Portal Tlalnepantla",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99090148
    },
    {
      "SAP": "T157",
      "ACTIVO": 21090016,
      "TIENDA": "Cac Acoxpa",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GARCIA ORTIZ CARLOS MANUEL",
      "STATUS": "",
      "IDPDV": 21090016
    },
    {
      "SAP": "T159",
      "ACTIVO": 38090006,
      "TIENDA": "Cac Altavista",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 38090006
    },
    {
      "SAP": "T161",
      "ACTIVO": 38090005,
      "TIENDA": "Cac Cc Comercial Santa Fe",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 38090005
    },
    {
      "SAP": "T166",
      "ACTIVO": 99090031,
      "TIENDA": "Cac Gran Sur Df",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090031
    },
    {
      "SAP": "T167",
      "ACTIVO": 38090001,
      "TIENDA": "Cac Insurgentes",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 38090001
    },
    {
      "SAP": "T168",
      "ACTIVO": 21090032,
      "TIENDA": "Cac Interlomas",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 21090032
    },
    {
      "SAP": "T424",
      "ACTIVO": 99090075,
      "TIENDA": "Cac Portal San Angel",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GUTIERREZ VALERO ROBERTO CARLOS",
      "STATUS": "",
      "IDPDV": 99090075
    },
    {
      "SAP": "T180",
      "ACTIVO": 21090008,
      "TIENDA": "Cac Torre Temm",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 21090008
    },
    {
      "SAP": "T189",
      "ACTIVO": 21090035,
      "TIENDA": "Mini Cac Centro Cuajimalpa",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 21090035
    },
    {
      "SAP": "T275",
      "ACTIVO": 99090059,
      "TIENDA": "Mini Cac Insurgentes Ii",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090059
    },
    {
      "SAP": "T537",
      "ACTIVO": 99090118,
      "TIENDA": "Mini Cac Las Aguilas Alvaro Obregon",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090118
    },
    {
      "SAP": "T544",
      "ACTIVO": 99090123,
      "TIENDA": "Mini Cac Patio Revolucion",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090123
    },
    {
      "SAP": "T218",
      "ACTIVO": 99090009,
      "TIENDA": "Smart Store Cc Comercial Santa Fe",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "FIGUEROA VALENCIA MARINA CIRA",
      "STATUS": "",
      "IDPDV": 99090009
    },
    {
      "SAP": "T250",
      "ACTIVO": 99090052,
      "TIENDA": "Smart Store Oasis Coyoacan",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090052
    },
    {
      "SAP": "T228",
      "ACTIVO": 99090006,
      "TIENDA": "Smart Store Pabellon Del Valle",
      "REGION": "",
      "TERRITORIO": "Centro Metropolitano",
      "SUBDIRECTOR": "",
      "COORDINADOR": "CARRILLO SANABRIA ENRIQUE ALONSO",
      "STATUS": "",
      "IDPDV": 99090006
    },
    {
      "SAP": "T035",
      "ACTIVO": 99030002,
      "TIENDA": "Cac Durango",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 99030002
    },
    {
      "SAP": "T492",
      "ACTIVO": 99030018,
      "TIENDA": "Cac Heb Revolucion Torreon",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 99030018
    },
    {
      "SAP": "T057",
      "ACTIVO": 99040009,
      "TIENDA": "Cac Monclova",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 99040009
    },
    {
      "SAP": "T039",
      "ACTIVO": 99030005,
      "TIENDA": "Cac Torreon",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 99030005
    },
    {
      "SAP": "T041",
      "ACTIVO": 21030015,
      "TIENDA": "Mini Cac Durango Centro",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 21030015
    },
    {
      "SAP": "T576",
      "ACTIVO": 99030033,
      "TIENDA": "Mini Cac Paseo Gomez Palacio",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 99030033
    },
    {
      "SAP": "T255",
      "ACTIVO": 99040024,
      "TIENDA": "Mini Cac Piedras Negras",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 99040024
    },
    {
      "SAP": "T047",
      "ACTIVO": 21030019,
      "TIENDA": "Mini Cac Torreon",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 21030019
    },
    {
      "SAP": "T329",
      "ACTIVO": 99030008,
      "TIENDA": "Plaza Movistar Torreon Centro",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SERRANO TORRES ROSA ELIA",
      "STATUS": "",
      "IDPDV": 99030008
    },
    {
      "SAP": "T049",
      "ACTIVO": 99040006,
      "TIENDA": "Cac Cd Victoria",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HONORATO BARRIENTOS MIREYA BERENICE",
      "STATUS": "",
      "IDPDV": 99040006
    },
    {
      "SAP": "T056",
      "ACTIVO": 21040008,
      "TIENDA": "Cac Matamoros",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HONORATO BARRIENTOS MIREYA BERENICE",
      "STATUS": "",
      "IDPDV": 21040008
    },
    {
      "SAP": "T059",
      "ACTIVO": 99040011,
      "TIENDA": "Cac Reynosa",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HONORATO BARRIENTOS MIREYA BERENICE",
      "STATUS": "",
      "IDPDV": 99040011
    },
    {
      "SAP": "T060",
      "ACTIVO": 99040012,
      "TIENDA": "Cac Reynosa Periferico",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HONORATO BARRIENTOS MIREYA BERENICE",
      "STATUS": "",
      "IDPDV": 99040012
    },
    {
      "SAP": "T064",
      "ACTIVO": 99040015,
      "TIENDA": "Cac Tampico",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HONORATO BARRIENTOS MIREYA BERENICE",
      "STATUS": "",
      "IDPDV": 99040015
    },
    {
      "SAP": "T065",
      "ACTIVO": 99040016,
      "TIENDA": "Cac Tampico Hidalgo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HONORATO BARRIENTOS MIREYA BERENICE",
      "STATUS": "",
      "IDPDV": 99040016
    },
    {
      "SAP": "T523",
      "ACTIVO": 99010022,
      "TIENDA": "Cac Alameda Otay Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010022
    },
    {
      "SAP": "T420",
      "ACTIVO": 99010012,
      "TIENDA": "Cac Constitucion Centro Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010012
    },
    {
      "SAP": "T002",
      "ACTIVO": 21010009,
      "TIENDA": "Cac Ensenada",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 21010009
    },
    {
      "SAP": "T407",
      "ACTIVO": 99010008,
      "TIENDA": "Cac Macro Plaza Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010008
    },
    {
      "SAP": "T415",
      "ACTIVO": 99010010,
      "TIENDA": "Cac Pacifico Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010010
    },
    {
      "SAP": "T007",
      "ACTIVO": 99010003,
      "TIENDA": "Cac Paseo De Los Heroes Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010003
    },
    {
      "SAP": "T504",
      "ACTIVO": 99010020,
      "TIENDA": "Cac Santa Fe Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010020
    },
    {
      "SAP": "T474",
      "ACTIVO": 99010015,
      "TIENDA": "Mini Cac Juarez Ensenada",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010015
    },
    {
      "SAP": "T531",
      "ACTIVO": 99010023,
      "TIENDA": "Mini Cac Plaza Loma Bonita Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010023
    },
    {
      "SAP": "T401",
      "ACTIVO": 99010009,
      "TIENDA": "Mini Cac Plaza Rio Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010009
    },
    {
      "SAP": "T013",
      "ACTIVO": 21010020,
      "TIENDA": "Mini Cac Rosarito",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 21010020
    },
    {
      "SAP": "T302",
      "ACTIVO": 99010006,
      "TIENDA": "Mini Cac Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010006
    },
    {
      "SAP": "T341",
      "ACTIVO": 99010004,
      "TIENDA": "Plaza Movistar Las Brisas Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ AZCARREGA ADRIAN",
      "STATUS": "",
      "IDPDV": 99010004
    },
    {
      "SAP": "T001",
      "ACTIVO": 21010011,
      "TIENDA": "Cac Cabo San Lucas",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 21010011
    },
    {
      "SAP": "T003",
      "ACTIVO": 21010002,
      "TIENDA": "Cac Galerias Del Valle",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 21010002
    },
    {
      "SAP": "T004",
      "ACTIVO": 21010016,
      "TIENDA": "Cac Justo Sierra Mexicali",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 21010016
    },
    {
      "SAP": "T005",
      "ACTIVO": 21010010,
      "TIENDA": "Cac Kino San Luis",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 21010010
    },
    {
      "SAP": "T006",
      "ACTIVO": 21010007,
      "TIENDA": "Cac La Paz",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 21010007
    },
    {
      "SAP": "T008",
      "ACTIVO": 21010006,
      "TIENDA": "Cac Paseo Tijuana 2000",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 21010006
    },
    {
      "SAP": "T403",
      "ACTIVO": 99010007,
      "TIENDA": "Cac Sendero Tijuana",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 99010007
    },
    {
      "SAP": "T011",
      "ACTIVO": 21010017,
      "TIENDA": "Mini Cac La Herradura",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 21010017
    },
    {
      "SAP": "T559",
      "ACTIVO": 99010026,
      "TIENDA": "Mini Cac Monarcas Mexicali",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 99010026
    },
    {
      "SAP": "T429",
      "ACTIVO": 99010013,
      "TIENDA": "Mini Cac Nuevo Mexicali",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 99010013
    },
    {
      "SAP": "T014",
      "ACTIVO": 21010022,
      "TIENDA": "Mini Cac San Pedro",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 21010022
    },
    {
      "SAP": "T560",
      "ACTIVO": 99010027,
      "TIENDA": "Mini Cac Sendero Mexicali",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99010027
    },
    {
      "SAP": "T340",
      "ACTIVO": 99010005,
      "TIENDA": "Plaza Movistar Mexicali",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SOLIZ VILLAGRANA CANDIDO ADRIAN",
      "STATUS": "",
      "IDPDV": 99010005
    },
    {
      "SAP": "T411",
      "ACTIVO": 99040039,
      "TIENDA": "Cac Alameda Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040039
    },
    {
      "SAP": "T052",
      "ACTIVO": 99040007,
      "TIENDA": "Cac Galerias Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040007
    },
    {
      "SAP": "T053",
      "ACTIVO": 99040008,
      "TIENDA": "Cac La Fe Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040008
    },
    {
      "SAP": "T406",
      "ACTIVO": 99040036,
      "TIENDA": "Cac Morelos Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040036
    },
    {
      "SAP": "T058",
      "ACTIVO": 99040010,
      "TIENDA": "Cac Nuevo Laredo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040010
    },
    {
      "SAP": "T054",
      "ACTIVO": 21040037,
      "TIENDA": "Cac Plaza Fiesta Anahuac",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 21040037
    },
    {
      "SAP": "T408",
      "ACTIVO": 99040037,
      "TIENDA": "Cac Raul Salinas Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040037
    },
    {
      "SAP": "T061",
      "ACTIVO": 99040013,
      "TIENDA": "Cac Saltillo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040013
    },
    {
      "SAP": "T063",
      "ACTIVO": 21040007,
      "TIENDA": "Cac Santa Catarina Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 21040007
    },
    {
      "SAP": "T386",
      "ACTIVO": 99040035,
      "TIENDA": "Cac Sendero La Fe Apodaca",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040035
    },
    {
      "SAP": "T583",
      "ACTIVO": 99040065,
      "TIENDA": "Movistar Plaza Sendero Apodaca",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040065
    },
    {
      "SAP": "T477",
      "ACTIVO": 99040046,
      "TIENDA": "Cac Centro Cadereyta",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040046
    },
    {
      "SAP": "T051",
      "ACTIVO": 21040009,
      "TIENDA": "Cac Cumbres",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 21040009
    },
    {
      "SAP": "T414",
      "ACTIVO": 99040040,
      "TIENDA": "Cac Paseo Punto Poniente Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040040
    },
    {
      "SAP": "T055",
      "ACTIVO": 21040038,
      "TIENDA": "Cac Plaza Fiesta San Agustin",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 21040038
    },
    {
      "SAP": "T371",
      "ACTIVO": 99040030,
      "TIENDA": "Mini Cac Centrika Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040030
    },
    {
      "SAP": "T476",
      "ACTIVO": 99040048,
      "TIENDA": "Mini Cac Multiplaza Lindavista Guadalupe",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040048
    },
    {
      "SAP": "T483",
      "ACTIVO": 99040052,
      "TIENDA": "Mini Cac Sun Mall Vip Villa De Juarez",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040052
    },
    {
      "SAP": "T601",
      "ACTIVO": 99040068,
      "TIENDA": "Movistar Paseo Tec Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99040068
    },
    {
      "SAP": "T589",
      "ACTIVO": 99040067,
      "TIENDA": "Movistar Patio Lincoln Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040067
    },
    {
      "SAP": "T326",
      "ACTIVO": 99040018,
      "TIENDA": "Plaza Movistar Soriana San Pedro",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99040018
    },
    {
      "SAP": "T344",
      "ACTIVO": 99040028,
      "TIENDA": "Plaza Movistar Sunmall",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040028
    },
    {
      "SAP": "T355",
      "ACTIVO": 99040021,
      "TIENDA": "Smart Store Plaza Real",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PEREZ HERNANDEZ MARIA GUADALUPE",
      "STATUS": "",
      "IDPDV": 99040021
    },
    {
      "SAP": "T541",
      "ACTIVO": 99040059,
      "TIENDA": "Cac Altea Lincoln Monterrey",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040059
    },
    {
      "SAP": "T062",
      "ACTIVO": 99040014,
      "TIENDA": "Cac Saltillo Ii",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040014
    },
    {
      "SAP": "T388",
      "ACTIVO": 99040034,
      "TIENDA": "Mini Cac Paseo La Fe Nuevo Leon",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040034
    },
    {
      "SAP": "T404",
      "ACTIVO": 99040038,
      "TIENDA": "Mini Cac Plazoleta Garcia",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040038
    },
    {
      "SAP": "T493",
      "ACTIVO": 99040053,
      "TIENDA": "Mini Cac Santo Domingo San Nicolas De Los Garza",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040053
    },
    {
      "SAP": "T458",
      "ACTIVO": 99040044,
      "TIENDA": "Mini Cac Sendero Sur Saltillo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040044
    },
    {
      "SAP": "T478",
      "ACTIVO": 99040058,
      "TIENDA": "Mini Cac Zocalo Apodaca",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040058
    },
    {
      "SAP": "T588",
      "ACTIVO": 99040066,
      "TIENDA": "Movistar Patio Saltillo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040066
    },
    {
      "SAP": "T581",
      "ACTIVO": 99040064,
      "TIENDA": "Movistar Plaza Sendero Escobedo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99040064
    },
    {
      "SAP": "T356",
      "ACTIVO": 1041699,
      "TIENDA": "Plaza Movistar Galerias Saltillo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 1041699
    },
    {
      "SAP": "T336",
      "ACTIVO": 99040022,
      "TIENDA": "Smart Store Nuevo Sur",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALAS VARGAS ANA LILIA",
      "STATUS": "",
      "IDPDV": 99040022
    },
    {
      "SAP": "T325",
      "ACTIVO": 99040019,
      "TIENDA": "Smart Store Plaza Antalya",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99040019
    },
    {
      "SAP": "T033",
      "ACTIVO": 21030002,
      "TIENDA": "Cac Cuauhtemoc",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 21030002
    },
    {
      "SAP": "T034",
      "ACTIVO": 21030004,
      "TIENDA": "Cac Delicias",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 21030004
    },
    {
      "SAP": "T487",
      "ACTIVO": 99030017,
      "TIENDA": "Cac Nueva Espa�a Chihuahua",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 99030017
    },
    {
      "SAP": "T038",
      "ACTIVO": 99030004,
      "TIENDA": "Cac Plaza San Agustin",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 99030004
    },
    {
      "SAP": "T506",
      "ACTIVO": 99030021,
      "TIENDA": "Cac Sendero Chihuahua",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 99030021
    },
    {
      "SAP": "T042",
      "ACTIVO": 21030014,
      "TIENDA": "Mini Cac Fashion Mall Chihuahua",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 21030014
    },
    {
      "SAP": "T500",
      "ACTIVO": 99030020,
      "TIENDA": "Mini Cac Independencia Chihuahua",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 99030020
    },
    {
      "SAP": "T045",
      "ACTIVO": 21030017,
      "TIENDA": "Mini Cac Plaza Galerias",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 21030017
    },
    {
      "SAP": "T046",
      "ACTIVO": 21030013,
      "TIENDA": "Mini Cac Plaza Vallarta (Chihuahua)",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ALDERETE JUAREZ JAVIER IVAN",
      "STATUS": "",
      "IDPDV": 21030013
    },
    {
      "SAP": "T416",
      "ACTIVO": 99030015,
      "TIENDA": "Cac Benito Juarez Ciudad Juarez",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MANRIQUEZ MU�OZ VICTOR MANUEL",
      "STATUS": "",
      "IDPDV": 99030015
    },
    {
      "SAP": "T036",
      "ACTIVO": 99030003,
      "TIENDA": "Cac Las Misiones Juarez",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MANRIQUEZ MU�OZ VICTOR MANUEL",
      "STATUS": "",
      "IDPDV": 99030003
    },
    {
      "SAP": "T447",
      "ACTIVO": 99030016,
      "TIENDA": "Cac Sendero Ciudad Juarez",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MANRIQUEZ MU�OZ VICTOR MANUEL",
      "STATUS": "",
      "IDPDV": 99030016
    },
    {
      "SAP": "T363",
      "ACTIVO": 99030011,
      "TIENDA": "Cac Sendero Las Torres",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MANRIQUEZ MU�OZ VICTOR MANUEL",
      "STATUS": "",
      "IDPDV": 99030011
    },
    {
      "SAP": "T040",
      "ACTIVO": 99030006,
      "TIENDA": "Cac Zaragoza Juarez",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MANRIQUEZ MU�OZ VICTOR MANUEL",
      "STATUS": "",
      "IDPDV": 99030006
    },
    {
      "SAP": "T495",
      "ACTIVO": 99030019,
      "TIENDA": "Mini Cac Galerias Tec Cd Juarez",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MANRIQUEZ MU�OZ VICTOR MANUEL",
      "STATUS": "",
      "IDPDV": 99030019
    },
    {
      "SAP": "T017",
      "ACTIVO": 21020009,
      "TIENDA": "Cac Hermosillo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 21020009
    },
    {
      "SAP": "T020",
      "ACTIVO": 21020025,
      "TIENDA": "Cac Nogales",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 21020025
    },
    {
      "SAP": "T021",
      "ACTIVO": 21020008,
      "TIENDA": "Cac Obregon",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 21020008
    },
    {
      "SAP": "T521",
      "ACTIVO": 99020014,
      "TIENDA": "Cac Plaza Quiroga Hermosillo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 99020014
    },
    {
      "SAP": "T024",
      "ACTIVO": 21020038,
      "TIENDA": "Mini Cac Guaymas",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 21020038
    },
    {
      "SAP": "T023",
      "ACTIVO": 21020029,
      "TIENDA": "Mini Cac Hermosillo Sendero",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 21020029
    },
    {
      "SAP": "T029",
      "ACTIVO": 21020039,
      "TIENDA": "Mini Cac Navojoa",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 21020039
    },
    {
      "SAP": "T547",
      "ACTIVO": 99020015,
      "TIENDA": "Mini Cac Sun Mall Hermosillo",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 99020015
    },
    {
      "SAP": "T364",
      "ACTIVO": 1020941,
      "TIENDA": "Plaza Movistar City Center Pitic",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "BOURS SONQUI GERMAN HUMBERTO",
      "STATUS": "",
      "IDPDV": 1020941
    },
    {
      "SAP": "T323",
      "ACTIVO": 99020003,
      "TIENDA": "Smart Store Galerias Mall Sonora",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99020003
    },
    {
      "SAP": "T016",
      "ACTIVO": 21020035,
      "TIENDA": "Cac Culiacan",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 21020035
    },
    {
      "SAP": "T575",
      "ACTIVO": 99020017,
      "TIENDA": "Cac Explanada Culiacan",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 99020017
    },
    {
      "SAP": "T462",
      "ACTIVO": 99020012,
      "TIENDA": "Cac Insurgentes Culiacan",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 99020012
    },
    {
      "SAP": "T018",
      "ACTIVO": 99020002,
      "TIENDA": "Cac Los Mochis",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 99020002
    },
    {
      "SAP": "T019",
      "ACTIVO": 21020007,
      "TIENDA": "Cac Mazatlan",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 21020007
    },
    {
      "SAP": "T435",
      "ACTIVO": 99020010,
      "TIENDA": "Cac Obregon Culiacan",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 99020010
    },
    {
      "SAP": "T201",
      "ACTIVO": 99020005,
      "TIENDA": "Mini Cac Culiacan Centro",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 99020005
    },
    {
      "SAP": "T304",
      "ACTIVO": 99020004,
      "TIENDA": "Mini Cac Guasave",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 99020004
    },
    {
      "SAP": "T582",
      "ACTIVO": 99020019,
      "TIENDA": "Movistar Plaza Sendero Culiacan",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99020019
    },
    {
      "SAP": "T333",
      "ACTIVO": 99020007,
      "TIENDA": "Plaza Movistar Paseos Los Mochis",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 99020007
    },
    {
      "SAP": "T353",
      "ACTIVO": 99020009,
      "TIENDA": "Plaza Movistar San Isidro",
      "REGION": "",
      "TERRITORIO": "Norte",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SANZ RUBIO HADIT",
      "STATUS": "",
      "IDPDV": 99020009
    },
    {
      "SAP": "T446",
      "ACTIVO": 99070033,
      "TIENDA": "Cac Benito Juarez Celaya",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 99070033
    },
    {
      "SAP": "T121",
      "ACTIVO": 21070012,
      "TIENDA": "Cac Celaya",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 21070012
    },
    {
      "SAP": "T522",
      "ACTIVO": 99070049,
      "TIENDA": "Cac Paseo Queretaro",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 99070049
    },
    {
      "SAP": "T427",
      "ACTIVO": 99070029,
      "TIENDA": "Cac Plaza Antea Queretaro",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 99070029
    },
    {
      "SAP": "T126",
      "ACTIVO": 99070012,
      "TIENDA": "Cac Queretaro",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 99070012
    },
    {
      "SAP": "T127",
      "ACTIVO": 21070029,
      "TIENDA": "Cac Queretaro Universidad",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 21070029
    },
    {
      "SAP": "T392",
      "ACTIVO": 99070026,
      "TIENDA": "Mini Cac Benito Juarez Sur Queretaro",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 99070026
    },
    {
      "SAP": "T387",
      "ACTIVO": 99070025,
      "TIENDA": "Mini Cac Patio Queretaro",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 99070025
    },
    {
      "SAP": "T133",
      "ACTIVO": 21070016,
      "TIENDA": "Mini Cac Plaza Constituyentes",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 21070016
    },
    {
      "SAP": "T135",
      "ACTIVO": 21070020,
      "TIENDA": "Mini Cac Plaza Revolucion",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 21070020
    },
    {
      "SAP": "T602",
      "ACTIVO": 99070055,
      "TIENDA": "Movistar Plaza Ubika Universidad Quer�taro",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "GONZALEZ FARFAN EMMANUEL",
      "STATUS": "",
      "IDPDV": 99070055
    },
    {
      "SAP": "T099",
      "ACTIVO": 21060015,
      "TIENDA": "Cac Lazaro Cardenas",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMOS GONZALEZ FERNANDO",
      "STATUS": "",
      "IDPDV": 21060015
    },
    {
      "SAP": "T100",
      "ACTIVO": 21060019,
      "TIENDA": "Cac Morelia",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMOS GONZALEZ FERNANDO",
      "STATUS": "",
      "IDPDV": 21060019
    },
    {
      "SAP": "T101",
      "ACTIVO": 21060018,
      "TIENDA": "Cac Morelia-2",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMOS GONZALEZ FERNANDO",
      "STATUS": "",
      "IDPDV": 21060018
    },
    {
      "SAP": "T486",
      "ACTIVO": 99060045,
      "TIENDA": "Cac Prados Camelinas Morelia",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMOS GONZALEZ FERNANDO",
      "STATUS": "",
      "IDPDV": 99060045
    },
    {
      "SAP": "T107",
      "ACTIVO": 21060016,
      "TIENDA": "Cac Uruapan",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMOS GONZALEZ FERNANDO",
      "STATUS": "",
      "IDPDV": 21060016
    },
    {
      "SAP": "T482",
      "ACTIVO": 99060043,
      "TIENDA": "Mini Cac Mercado Independencia Morelia",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMOS GONZALEZ FERNANDO",
      "STATUS": "",
      "IDPDV": 99060043
    },
    {
      "SAP": "T119",
      "ACTIVO": 21040024,
      "TIENDA": "Mini Cac Morelia Estadio",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMOS GONZALEZ FERNANDO",
      "STATUS": "",
      "IDPDV": 21040024
    },
    {
      "SAP": "T097",
      "ACTIVO": 21060017,
      "TIENDA": "Cac Centro Sur",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 21060017
    },
    {
      "SAP": "T375",
      "ACTIVO": 99060028,
      "TIENDA": "Cac Chapultepec",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060028
    },
    {
      "SAP": "T108",
      "ACTIVO": 99060008,
      "TIENDA": "Cac Guadalajara Centro Historico",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060008
    },
    {
      "SAP": "T103",
      "ACTIVO": 21060014,
      "TIENDA": "Cac Plaza Galerias",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 21060014
    },
    {
      "SAP": "T460",
      "ACTIVO": 99060037,
      "TIENDA": "Cac Plaza Patria Guadalajara",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060037
    },
    {
      "SAP": "T105",
      "ACTIVO": 99060009,
      "TIENDA": "Cac Revolucion Guadalajara",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060009
    },
    {
      "SAP": "T391",
      "ACTIVO": 99060030,
      "TIENDA": "Cac Transito Guadalajara",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060030
    },
    {
      "SAP": "T577",
      "ACTIVO": 99060056,
      "TIENDA": "Mini Cac Multiplaza Del Valle",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060056
    },
    {
      "SAP": "T115",
      "ACTIVO": 21060031,
      "TIENDA": "Mini Cac Plaza Regina",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 21060031
    },
    {
      "SAP": "T479",
      "ACTIVO": 99060041,
      "TIENDA": "Mini Cac Urbancenter Guadalajara",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060041
    },
    {
      "SAP": "T317",
      "ACTIVO": 99060012,
      "TIENDA": "Plaza Movistar Estadio Jalisco",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060012
    },
    {
      "SAP": "T316",
      "ACTIVO": 99060015,
      "TIENDA": "Smart Store Plaza San Miguel",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060015
    },
    {
      "SAP": "T102",
      "ACTIVO": 21060023,
      "TIENDA": "Cac Plaza Del Sol",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 21060023
    },
    {
      "SAP": "T572",
      "ACTIVO": 99060055,
      "TIENDA": "Mini Cac Independencia Centro Guadalajara",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060055
    },
    {
      "SAP": "T571",
      "ACTIVO": 99060054,
      "TIENDA": "Mini Cac Juarez Centro Guadalajara",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "-",
      "STATUS": "",
      "IDPDV": 99060054
    },
    {
      "SAP": "T569",
      "ACTIVO": 99060053,
      "TIENDA": "Mini Cac Plaza Lomas Tonal�",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060053
    },
    {
      "SAP": "T461",
      "ACTIVO": 99060038,
      "TIENDA": "Mini Cac Punto San Isidro Guadalajara",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060038
    },
    {
      "SAP": "T533",
      "ACTIVO": 99060049,
      "TIENDA": "Mini Cac San Juan Bosco Guadalajara",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060049
    },
    {
      "SAP": "T592",
      "ACTIVO": 99060058,
      "TIENDA": "Movistar Midtown Jalisco",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060058
    },
    {
      "SAP": "T585",
      "ACTIVO": 99060057,
      "TIENDA": "Movistar Plaza Fiesta Arboledas",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060057
    },
    {
      "SAP": "T365",
      "ACTIVO": 1062036,
      "TIENDA": "Plaza Movistar Las Torres",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 1062036
    },
    {
      "SAP": "T366",
      "ACTIVO": 1062035,
      "TIENDA": "Plaza Movistar Tonala",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 1062035
    },
    {
      "SAP": "T354",
      "ACTIVO": 99060010,
      "TIENDA": "Smart Store Gran Terraza Belenes",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060010
    },
    {
      "SAP": "T314",
      "ACTIVO": 99060011,
      "TIENDA": "Smart Store Gran Terraza Oblatos",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060011
    },
    {
      "SAP": "T322",
      "ACTIVO": 99060013,
      "TIENDA": "Smart Store Plaza Del Sol",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060013
    },
    {
      "SAP": "T315",
      "ACTIVO": 99060014,
      "TIENDA": "Smart Store Real Center",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SALDA�A ROBINA JOSE MAURICIO",
      "STATUS": "",
      "IDPDV": 99060014
    },
    {
      "SAP": "T457",
      "ACTIVO": 99070036,
      "TIENDA": "Cac Escobedo Leon",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 99070036
    },
    {
      "SAP": "T122",
      "ACTIVO": 21070009,
      "TIENDA": "Cac Irapuato",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 21070009
    },
    {
      "SAP": "T123",
      "ACTIVO": 21070011,
      "TIENDA": "Cac Leon",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 21070011
    },
    {
      "SAP": "T124",
      "ACTIVO": 21070010,
      "TIENDA": "Cac Leon Ii",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 21070010
    },
    {
      "SAP": "T130",
      "ACTIVO": 21070017,
      "TIENDA": "Mini Cac Galeria Las Torres",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 21070017
    },
    {
      "SAP": "T268",
      "ACTIVO": 99070022,
      "TIENDA": "Mini Cac Obelisco",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 99070022
    },
    {
      "SAP": "T264",
      "ACTIVO": 99070019,
      "TIENDA": "Mini Cac Salamanca",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 99070019
    },
    {
      "SAP": "T468",
      "ACTIVO": 99070038,
      "TIENDA": "Mini Cac San Juan Bosco Leon",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 99070038
    },
    {
      "SAP": "T441",
      "ACTIVO": 99070032,
      "TIENDA": "Mini Cac Torres Landa Leon",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 99070032
    },
    {
      "SAP": "T580",
      "ACTIVO": 99070054,
      "TIENDA": "Movistar Plaza Walmart Torreslanda",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 99070054
    },
    {
      "SAP": "T324",
      "ACTIVO": 99070013,
      "TIENDA": "Plaza Movistar Irapuato",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 99070013
    },
    {
      "SAP": "T331",
      "ACTIVO": 99070015,
      "TIENDA": "Plaza Movistar Leon Centro",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RIVERA RUBIO NOE EDUARDO",
      "STATUS": "",
      "IDPDV": 99070015
    },
    {
      "SAP": "T098",
      "ACTIVO": 21060012,
      "TIENDA": "Cac Colima",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HERNANDEZ CASTELLANOS CARLOS ROBERTO",
      "STATUS": "",
      "IDPDV": 21060012
    },
    {
      "SAP": "T393",
      "ACTIVO": 99060031,
      "TIENDA": "Cac Forum Tepic",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HERNANDEZ CASTELLANOS CARLOS ROBERTO",
      "STATUS": "",
      "IDPDV": 99060031
    },
    {
      "SAP": "T104",
      "ACTIVO": 21060013,
      "TIENDA": "Cac Puerto Vallarta",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HERNANDEZ CASTELLANOS CARLOS ROBERTO",
      "STATUS": "",
      "IDPDV": 21060013
    },
    {
      "SAP": "T106",
      "ACTIVO": 21060024,
      "TIENDA": "Cac Tepic",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HERNANDEZ CASTELLANOS CARLOS ROBERTO",
      "STATUS": "",
      "IDPDV": 21060024
    },
    {
      "SAP": "T265",
      "ACTIVO": 99060024,
      "TIENDA": "Mini Cac Manzanillo",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HERNANDEZ CASTELLANOS CARLOS ROBERTO",
      "STATUS": "",
      "IDPDV": 99060024
    },
    {
      "SAP": "T112",
      "ACTIVO": 21060039,
      "TIENDA": "Mini Cac Plaza Lago Real",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HERNANDEZ CASTELLANOS CARLOS ROBERTO",
      "STATUS": "",
      "IDPDV": 21060039
    },
    {
      "SAP": "T620",
      "ACTIVO": 99060061,
      "TIENDA": "Movistar Galerias Vallarta",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "HERNANDEZ CASTELLANOS CARLOS ROBERTO",
      "STATUS": "",
      "IDPDV": 99060061
    },
    {
      "SAP": "T120",
      "ACTIVO": 21070008,
      "TIENDA": "Cac Aguascalientes",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ARRIAGA ESPARZA FRANCISCO ALEJANDRO",
      "STATUS": "",
      "IDPDV": 21070008
    },
    {
      "SAP": "T370",
      "ACTIVO": 99070024,
      "TIENDA": "Cac Morelos Aguascalientes",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ARRIAGA ESPARZA FRANCISCO ALEJANDRO",
      "STATUS": "",
      "IDPDV": 99070024
    },
    {
      "SAP": "T129",
      "ACTIVO": 21070013,
      "TIENDA": "Cac Zacatecas",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ARRIAGA ESPARZA FRANCISCO ALEJANDRO",
      "STATUS": "",
      "IDPDV": 21070013
    },
    {
      "SAP": "T267",
      "ACTIVO": 99070018,
      "TIENDA": "Mini Cac Fresnillo",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ARRIAGA ESPARZA FRANCISCO ALEJANDRO",
      "STATUS": "",
      "IDPDV": 99070018
    },
    {
      "SAP": "T497",
      "ACTIVO": 99070044,
      "TIENDA": "Mini Cac Parque Hidalgo Aguascalientes",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ARRIAGA ESPARZA FRANCISCO ALEJANDRO",
      "STATUS": "",
      "IDPDV": 99070044
    },
    {
      "SAP": "T450",
      "ACTIVO": 99070034,
      "TIENDA": "Mini Cac Plaza Guadalupe Aguascalientes",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ARRIAGA ESPARZA FRANCISCO ALEJANDRO",
      "STATUS": "",
      "IDPDV": 99070034
    },
    {
      "SAP": "T136",
      "ACTIVO": 21070018,
      "TIENDA": "Mini Cac Plaza Velaria Mall",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ARRIAGA ESPARZA FRANCISCO ALEJANDRO",
      "STATUS": "",
      "IDPDV": 21070018
    },
    {
      "SAP": "T137",
      "ACTIVO": 21070028,
      "TIENDA": "Mini Cac Plaza Villa Asuncion",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "ARRIAGA ESPARZA FRANCISCO ALEJANDRO",
      "STATUS": "",
      "IDPDV": 21070028
    },
    {
      "SAP": "T200",
      "ACTIVO": 21070038,
      "TIENDA": "Cac Carranza",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SILVA SANCHEZ JOSE GUADALUPE",
      "STATUS": "",
      "IDPDV": 21070038
    },
    {
      "SAP": "T514",
      "ACTIVO": 99070048,
      "TIENDA": "Cac Centro San Luis",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SILVA SANCHEZ JOSE GUADALUPE",
      "STATUS": "",
      "IDPDV": 99070048
    },
    {
      "SAP": "T128",
      "ACTIVO": 21070006,
      "TIENDA": "Cac San Luis Potosi",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SILVA SANCHEZ JOSE GUADALUPE",
      "STATUS": "",
      "IDPDV": 21070006
    },
    {
      "SAP": "T132",
      "ACTIVO": 21070027,
      "TIENDA": "Mini Cac Plaza Constitucion",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SILVA SANCHEZ JOSE GUADALUPE",
      "STATUS": "",
      "IDPDV": 21070027
    },
    {
      "SAP": "T428",
      "ACTIVO": 99070030,
      "TIENDA": "Mini Cac Plaza Del Carmen San Luis Potosi (Plaza De La Tecnologia)",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SILVA SANCHEZ JOSE GUADALUPE",
      "STATUS": "",
      "IDPDV": 99070030
    },
    {
      "SAP": "T472",
      "ACTIVO": 99070040,
      "TIENDA": "Mini Cac Sendero San Luis",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SILVA SANCHEZ JOSE GUADALUPE",
      "STATUS": "",
      "IDPDV": 99070040
    },
    {
      "SAP": "T361",
      "ACTIVO": 1071966,
      "TIENDA": "Plaza Movistar San Luis Potosi",
      "REGION": "",
      "TERRITORIO": "Occidente",
      "SUBDIRECTOR": "",
      "COORDINADOR": "SILVA SANCHEZ JOSE GUADALUPE",
      "STATUS": "",
      "IDPDV": 1071966
    },
    {
      "SAP": "T069",
      "ACTIVO": 21050020,
      "TIENDA": "Cac Cancun",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MORALES LOPEZ VICTOR HUGO",
      "STATUS": "",
      "IDPDV": 21050020
    },
    {
      "SAP": "T072",
      "ACTIVO": 21050022,
      "TIENDA": "Cac Chetumal",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MORALES LOPEZ VICTOR HUGO",
      "STATUS": "",
      "IDPDV": 21050022
    },
    {
      "SAP": "T199",
      "ACTIVO": 21050036,
      "TIENDA": "Cac La Gran Plaza Cancun",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MORALES LOPEZ VICTOR HUGO",
      "STATUS": "",
      "IDPDV": 21050036
    },
    {
      "SAP": "T096",
      "ACTIVO": 21050048,
      "TIENDA": "Mini Cac Las Americas Cancun",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MORALES LOPEZ VICTOR HUGO",
      "STATUS": "",
      "IDPDV": 21050048
    },
    {
      "SAP": "T088",
      "ACTIVO": 21050031,
      "TIENDA": "Mini Cac Multiplaza Kabah",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MORALES LOPEZ VICTOR HUGO",
      "STATUS": "",
      "IDPDV": 21050031
    },
    {
      "SAP": "T094",
      "ACTIVO": 21050027,
      "TIENDA": "Mini Cac Plaza Inn Cancun",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MORALES LOPEZ VICTOR HUGO",
      "STATUS": "",
      "IDPDV": 21050027
    },
    {
      "SAP": "T089",
      "ACTIVO": 21050050,
      "TIENDA": "Mini Cac Plaza Villas Del Mar",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MORALES LOPEZ VICTOR HUGO",
      "STATUS": "",
      "IDPDV": 21050050
    },
    {
      "SAP": "T068",
      "ACTIVO": 21050013,
      "TIENDA": "Cac Campeche",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 21050013
    },
    {
      "SAP": "T071",
      "ACTIVO": 21050016,
      "TIENDA": "Cac Cd. Del Carmen",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 21050016
    },
    {
      "SAP": "T075",
      "ACTIVO": 21050012,
      "TIENDA": "Cac Merida",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 21050012
    },
    {
      "SAP": "T086",
      "ACTIVO": 21050034,
      "TIENDA": "Mini Cac Gran Plaza Merida",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 21050034
    },
    {
      "SAP": "T092",
      "ACTIVO": 21050042,
      "TIENDA": "Mini Cac Plaza Dorada",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 21050042
    },
    {
      "SAP": "T519",
      "ACTIVO": 99050034,
      "TIENDA": "Mini Cac Plaza Kukulkan Merida",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 99050034
    },
    {
      "SAP": "T593",
      "ACTIVO": 99050036,
      "TIENDA": "Movistar Macroplaza Merida",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 99050036
    },
    {
      "SAP": "T594",
      "ACTIVO": 99050037,
      "TIENDA": "Movistar Plaza La Isla Merida",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 99050037
    },
    {
      "SAP": "T312",
      "ACTIVO": 99050013,
      "TIENDA": "Plaza Movistar Galerias Campeche",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 99050013
    },
    {
      "SAP": "T297",
      "ACTIVO": 99050016,
      "TIENDA": "Plaza Movistar Merida 56",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 99050016
    },
    {
      "SAP": "T313",
      "ACTIVO": 99050014,
      "TIENDA": "Smart Store Galerias Merida",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "RAMIREZ HUICAB JESUS FELIPE",
      "STATUS": "",
      "IDPDV": 99050014
    },
    {
      "SAP": "T139",
      "ACTIVO": 21080008,
      "TIENDA": "Cac Cordoba",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ GARCIA ERIKA FERNANDA",
      "STATUS": "",
      "IDPDV": 21080008
    },
    {
      "SAP": "T148",
      "ACTIVO": 21080023,
      "TIENDA": "Cac Orizaba",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ GARCIA ERIKA FERNANDA",
      "STATUS": "",
      "IDPDV": 21080023
    },
    {
      "SAP": "T141",
      "ACTIVO": 99080007,
      "TIENDA": "Cac Poza Rica",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ GARCIA ERIKA FERNANDA",
      "STATUS": "",
      "IDPDV": 99080007
    },
    {
      "SAP": "T144",
      "ACTIVO": 99080009,
      "TIENDA": "Cac Veracruz",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ GARCIA ERIKA FERNANDA",
      "STATUS": "",
      "IDPDV": 99080009
    },
    {
      "SAP": "T145",
      "ACTIVO": 21080006,
      "TIENDA": "Cac Veracruz Ii",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ GARCIA ERIKA FERNANDA",
      "STATUS": "",
      "IDPDV": 21080006
    },
    {
      "SAP": "T146",
      "ACTIVO": 99080010,
      "TIENDA": "Cac Xalapa",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ GARCIA ERIKA FERNANDA",
      "STATUS": "",
      "IDPDV": 99080010
    },
    {
      "SAP": "T151",
      "ACTIVO": 21080014,
      "TIENDA": "Mini Cac El Dorado",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ GARCIA ERIKA FERNANDA",
      "STATUS": "",
      "IDPDV": 21080014
    },
    {
      "SAP": "T349",
      "ACTIVO": 99080014,
      "TIENDA": "Plaza Movistar Tuxpan",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "LOPEZ GARCIA ERIKA FERNANDA",
      "STATUS": "",
      "IDPDV": 99080014
    },
    {
      "SAP": "T070",
      "ACTIVO": 21050014,
      "TIENDA": "Cac Cardenas",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PIZANO MORENO HECTOR ADRIAN",
      "STATUS": "",
      "IDPDV": 21050014
    },
    {
      "SAP": "T073",
      "ACTIVO": 21050019,
      "TIENDA": "Cac Comalcalco",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PIZANO MORENO HECTOR ADRIAN",
      "STATUS": "",
      "IDPDV": 21050019
    },
    {
      "SAP": "T077",
      "ACTIVO": 21050015,
      "TIENDA": "Cac Tapachula",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PIZANO MORENO HECTOR ADRIAN",
      "STATUS": "",
      "IDPDV": 21050015
    },
    {
      "SAP": "T078",
      "ACTIVO": 99050009,
      "TIENDA": "Cac Tuxtla Gutierrez",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PIZANO MORENO HECTOR ADRIAN",
      "STATUS": "",
      "IDPDV": 99050009
    },
    {
      "SAP": "T079",
      "ACTIVO": 99050010,
      "TIENDA": "Cac Villahermosa",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PIZANO MORENO HECTOR ADRIAN",
      "STATUS": "",
      "IDPDV": 99050010
    },
    {
      "SAP": "T080",
      "ACTIVO": 21050037,
      "TIENDA": "Mini Cac Aldama Zona Luz",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PIZANO MORENO HECTOR ADRIAN",
      "STATUS": "",
      "IDPDV": 21050037
    },
    {
      "SAP": "T327",
      "ACTIVO": 99050020,
      "TIENDA": "Plaza Movistar Av. Francisco Javier Mina",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PIZANO MORENO HECTOR ADRIAN",
      "STATUS": "",
      "IDPDV": 99050020
    },
    {
      "SAP": "T342",
      "ACTIVO": 99050019,
      "TIENDA": "Plaza Movistar Punto Pino Suarez",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "PIZANO MORENO HECTOR ADRIAN",
      "STATUS": "",
      "IDPDV": 99050019
    },
    {
      "SAP": "T480",
      "ACTIVO": 99080028,
      "TIENDA": "Cac 2 Poniente Centro Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080028
    },
    {
      "SAP": "T524",
      "ACTIVO": 99080030,
      "TIENDA": "Cac Explanada Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080030
    },
    {
      "SAP": "T426",
      "ACTIVO": 99080027,
      "TIENDA": "Cac Parque Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080027
    },
    {
      "SAP": "T142",
      "ACTIVO": 99080008,
      "TIENDA": "Cac Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080008
    },
    {
      "SAP": "T147",
      "ACTIVO": 21080005,
      "TIENDA": "Cac Puebla Pabellon Dorada",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 21080005
    },
    {
      "SAP": "T155",
      "ACTIVO": 21080010,
      "TIENDA": "Cac San Andres",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 21080010
    },
    {
      "SAP": "T149",
      "ACTIVO": 21080022,
      "TIENDA": "Cac Tehuacan Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 21080022
    },
    {
      "SAP": "T372",
      "ACTIVO": 99080024,
      "TIENDA": "Cac Tlaxcala Plaza Inn",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080024
    },
    {
      "SAP": "T367",
      "ACTIVO": 99080023,
      "TIENDA": "Mini Cac Periplaza Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080023
    },
    {
      "SAP": "T397",
      "ACTIVO": 99080025,
      "TIENDA": "Mini Cac Plaza Margarita Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080025
    },
    {
      "SAP": "T563",
      "ACTIVO": 99080033,
      "TIENDA": "Mini Cac Plaza Norte Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080033
    },
    {
      "SAP": "T564",
      "ACTIVO": 99080034,
      "TIENDA": "Mini Cac Plaza San Sebastian Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080034
    },
    {
      "SAP": "T561",
      "ACTIVO": 99080032,
      "TIENDA": "Mini Cac Solesta Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080032
    },
    {
      "SAP": "T156",
      "ACTIVO": 21080015,
      "TIENDA": "Mini Cac Soriana Capu",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 21080015
    },
    {
      "SAP": "T281",
      "ACTIVO": 99080015,
      "TIENDA": "Mini Cac Tlaxcala",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080015
    },
    {
      "SAP": "T402",
      "ACTIVO": 99080026,
      "TIENDA": "Mini Cac Via San Angel Puebla",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080026
    },
    {
      "SAP": "T234",
      "ACTIVO": 99080002,
      "TIENDA": "Smart Store Galerias Hermanos Serdan",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "MARTINEZ GONZALEZ CESAR AUGUSTO",
      "STATUS": "",
      "IDPDV": 99080002
    },
    {
      "SAP": "T138",
      "ACTIVO": 99050011,
      "TIENDA": "Cac Coatzacoalcos",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "TOBON ROSAS JUAN MANUEL",
      "STATUS": "",
      "IDPDV": 99050011
    },
    {
      "SAP": "T140",
      "ACTIVO": 21080007,
      "TIENDA": "Cac Oaxaca",
      "REGION": "",
      "TERRITORIO": "Sur",
      "SUBDIRECTOR": "",
      "COORDINADOR": "TOBON ROSAS JUAN MANUEL",
      "STATUS": "",
      "IDPDV": 21080007
    }
  ]
  

  constructor(private afs: AngularFirestore) {
    // this.itemsCollection = this.afs.collection("Tiendas");
  }

  obtenerTiendas(){
    // return this.itemsCollection.valueChanges()
  }

}
